# Generated by Django 3.2 on 2022-09-17 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clgapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recordedclass',
            new_name='Recorded',
        ),
    ]
