# Generated by Django 3.2 on 2022-09-17 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clgapp', '0002_rename_recordedclass_recorded'),
    ]

    operations = [
        migrations.CreateModel(
            name='Studymaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=250, null=True)),
                ('pdfnote', models.ImageField(upload_to='media')),
                ('thumb', models.ImageField(blank=True, max_length=250, null=True, upload_to='media')),
                ('portions_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='clgapp.portions')),
            ],
        ),
    ]
