# Generated by Django 3.0.5 on 2022-09-22 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clgapp', '0005_delete_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admsnfee', models.CharField(default=0, max_length=1000)),
                ('tutfee', models.CharField(default=0, max_length=1000)),
                ('exmfee', models.CharField(default=0, max_length=1000)),
                ('busfee', models.CharField(default=0, max_length=1000)),
                ('labfee', models.CharField(default=0, max_length=1000)),
                ('unifee', models.CharField(default=0, max_length=1000)),
                ('status', models.CharField(default=0, max_length=1000)),
                ('student_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='clgapp.Admission')),
            ],
        ),
    ]
