# Generated by Django 3.0.5 on 2022-09-23 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clgapp', '0006_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='online',
            name='status',
            field=models.CharField(default='True', max_length=250),
        ),
    ]
